apiVersion: apps/v1
kind: Deployment
metadata:
  name: cry-deployment
  namespace: cry
  labels:
    app: cry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cry
  template:
    metadata:
      labels:
        app: cry
    spec:
      containers:
        - name: cry
          image: h3poteto/playground-cry:latest
